version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432"
    #environment:
    #  MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    #  MYSQL_ROOT_PASSWORD: hogejiro
    #  MYSQL_USER: root
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: $RAILS_SECRET_KEY_ENV
      MYAPP_DATABASE_PASSWORD: $RAILS_DB_PASSWORD_ENV
      REDIS_URL: redis://redis:6379
  redis:
    image: redis:latest
    ports:
      - 6379:6379

